services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/scripts/init:/docker-entrypoint-initdb.d
      - ./src/main/resources/scripts/sql:/mnt/scripts/sql


volumes:
  postgres_data: